name: Publish New Library Release to PyPi

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install poetry  by snok
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: poetry install dependencies
        run: poetry install --no-interaction --no-root

      - name: poetry build
        run: poetry build

      - name: poetry config
        run: poetry config ${{ secrets.PYPI_TOKEN }}

      - name: poetry publish
        run: poetry publish
